# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\exit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExitWindow(object):
    
    def LoginWindow(self):
        from start import MainWindow
        self.ui = MainWindow()
        self.ui.show()

    def StudentWindow(self):
        from main_student import Ui_MainStudentWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainStudentWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, ExitWindow):
        ExitWindow.setObjectName("ExitWindow")
        ExitWindow.resize(480, 370)
        ExitWindow.setMinimumSize(QtCore.QSize(480, 370))
        ExitWindow.setMaximumSize(QtCore.QSize(480, 370))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExitWindow.setWindowIcon(icon)
        ExitWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ExitWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.525, y1:0, x2:0.537, y2:1, stop:0 rgba(209, 47, 8, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: 0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setStyleSheet("    font: 63 20pt \"Montserrat SemiBold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_3.setStyleSheet("background-color: 0;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")

##############

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.clicked.connect(self.LoginWindow)
        self.pushButton_3.clicked.connect(ExitWindow.close)

#############

        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

#############

        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.clicked.connect(self.StudentWindow)
        self.pushButton_4.clicked.connect(ExitWindow.close)

###############

        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        ExitWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExitWindow)
        QtCore.QMetaObject.connectSlotsByName(ExitWindow)

    def retranslateUi(self, ExitWindow):
        _translate = QtCore.QCoreApplication.translate
        ExitWindow.setWindowTitle(_translate("ExitWindow", "Выход"))
        self.label_5.setText(_translate("ExitWindow", "Вы точно хотите выйти?"))
        self.pushButton_3.setText(_translate("ExitWindow", "Выйти"))
        self.pushButton_4.setText(_translate("ExitWindow", "Назад"))
import img_py.img_logo_rc
