# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime,QDate, QTime, Qt, QRegExp
from PyQt5.QtWidgets import QTableWidgetItem, QApplication, QDialog, QMainWindow, QMessageBox, QPushButton
from PyQt5.QtGui import QRegExpValidator

from update_users import Ui_UpdateUserWindow
from add_user import Ui_RegWindow
from exit_student import Ui_ExitWindow
import pandas as pd

import webbrowser

import requests
from functools import partial

# DOCX
import docx # Подключение к docx
from docx.shared import Pt # Подключение размер шрифта

# ПОДКЛЮЧЕНИЕ К БД
import mysql.connector as mc

mydb = mc.connect(
     host="localhost",
     user="root",
     password="",
     database="foxskill"
)
print("Успешное подключение БД - Главное окно Студента")
mycursor = mydb.cursor()

class Ui_MainStudentWindow(object):

    def PayWindow_2(self):
        from pay_2 import Ui_PayWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def PayWindow_3(self):
        from pay_3 import Ui_PayWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def PayWindow_4(self):
        from pay_4 import Ui_PayWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def PayWindow_5(self):
        from pay_5 import Ui_PayWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def PayWindow_6(self):
        from pay_6 import Ui_PayWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def PayWindow_All(self):
        from pay_all import Ui_PayWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def PayWindow_2(self):
        from pay_2 import Ui_PayWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def ExitWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ExitWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainStudentWindow):
        MainStudentWindow.setObjectName("MainStudentWindow")
        MainStudentWindow.resize(1100, 600)
        MainStudentWindow.setMinimumSize(QtCore.QSize(1100, 600))
        MainStudentWindow.setMaximumSize(QtCore.QSize(1100, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainStudentWindow.setWindowIcon(icon)
        MainStudentWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainStudentWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.525, y1:0, x2:0.537, y2:1, stop:0 rgba(209, 47, 8, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setStyleSheet("background-color: 0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(18, 18, 18, 18)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(200, 50))
        self.label.setMaximumSize(QtCore.QSize(200, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/img/logo_text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: 0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setMinimumSize(QtCore.QSize(300, 300))
        self.frame_7.setMaximumSize(QtCore.QSize(300, 300))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setObjectName("gridLayout_2")

###########

        self.pushButton_17 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page_3))

#########

        self.pushButton_17.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_17.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)

#############

        self.pushButton_13 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page_2))

#############

        self.pushButton_13.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_13.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 3, 0, 1, 1)

############

        self.pushButton_12 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_12.clicked.connect(lambda: webbrowser.open('https://ktk40.ru/index.php/ru/'))

#############

        self.pushButton_12.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_12.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 2, 0, 1, 1)

############

        self.pushButton_15 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_15.clicked.connect(self.ExitWindow)
        self.pushButton_15.clicked.connect(MainStudentWindow.close)

############

        self.pushButton_15.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_15.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_7, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(29, 125, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.page_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setStyleSheet("    font: 63 20pt \"Montserrat SemiBold\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_3.setSpacing(25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)

##############

        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.textChanged.connect(self.fio)

#############

        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_5.setSpacing(25)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)

###########

        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_2.textChanged.connect(self.phone)

#############

        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_6.setSpacing(25)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)

#############

        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_3.textChanged.connect(self.email)

################

        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_7.setSpacing(25)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)

############

        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.textChanged.connect(self.age)

##############

        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)

##############

        self.pushButton_31 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_31.clicked.connect(self.insert_data)

##############

        self.pushButton_31.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_31.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_8.addWidget(self.pushButton_31)

#########

        self.pushButton_32 = QtWidgets.QPushButton(self.frame_5, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page))

############

        self.pushButton_32.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_32.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_8.addWidget(self.pushButton_32)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setStyleSheet("border: 0;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1098, 518))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 518))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_14.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.frame_15)
        self.label_3.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.horizontalLayout_10.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")

###############

        self.pushButton_25 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_25.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 1.docx"))

################

        self.pushButton_25.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_25.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_12.addWidget(self.pushButton_25)
        self.horizontalLayout_10.addWidget(self.frame_16)
        self.gridLayout_3.addWidget(self.frame_14, 0, 0, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.frame_12)
        self.frame_23.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_6 = QtWidgets.QLabel(self.frame_24)
        self.label_6.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_20.addWidget(self.label_6)
        self.horizontalLayout_19.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.frame_23)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")

#############

        self.pushButton_28 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_28.clicked.connect(self.PayWindow_2)

##############

        self.pushButton_28.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_28.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_21.addWidget(self.pushButton_28)
        self.horizontalLayout_19.addWidget(self.frame_25)
        self.gridLayout_3.addWidget(self.frame_23, 0, 1, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame_12)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_17.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.frame_18)
        self.label_4.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.horizontalLayout_13.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")

##########

        self.pushButton_26 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_26.clicked.connect(self.PayWindow_3)

############

        self.pushButton_26.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_26.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_15.addWidget(self.pushButton_26)
        self.horizontalLayout_13.addWidget(self.frame_19)
        self.gridLayout_3.addWidget(self.frame_17, 1, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.frame_12)
        self.frame_26.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_7 = QtWidgets.QLabel(self.frame_27)
        self.label_7.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_23.addWidget(self.label_7)
        self.horizontalLayout_22.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")

#############

        self.pushButton_29 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_29.clicked.connect(self.PayWindow_4)

#################

        self.pushButton_29.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_29.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_24.addWidget(self.pushButton_29)
        self.horizontalLayout_22.addWidget(self.frame_28)
        self.gridLayout_3.addWidget(self.frame_26, 1, 1, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame_12)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_20.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.frame_21)
        self.label_5.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.horizontalLayout_16.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")

##############

        self.pushButton_27 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_27.clicked.connect(self.PayWindow_5)

###############

        self.pushButton_27.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_27.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_18.addWidget(self.pushButton_27)
        self.horizontalLayout_16.addWidget(self.frame_22)
        self.gridLayout_3.addWidget(self.frame_20, 2, 0, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.frame_12)
        self.frame_29.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_8 = QtWidgets.QLabel(self.frame_30)
        self.label_8.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_26.addWidget(self.label_8)
        self.horizontalLayout_25.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")

#############

        self.pushButton_30 = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_30.clicked.connect(self.PayWindow_6)

#############

        self.pushButton_30.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_30.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_27.addWidget(self.pushButton_30)
        self.horizontalLayout_25.addWidget(self.frame_31)
        self.gridLayout_3.addWidget(self.frame_29, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setSpacing(12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)

###########

        self.pushButton_24 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_24.clicked.connect(self.PayWindow_All)

##############

        self.pushButton_24.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_24.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_9.addWidget(self.pushButton_24)

###########

        self.pushButton_23 = QtWidgets.QPushButton(self.frame_13, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page))

############
        
        self.pushButton_23.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_23.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_9.addWidget(self.pushButton_23)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        MainStudentWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainStudentWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainStudentWindow)

####################### БД #################################################

    def insert_data(self):

        fio = self.lineEdit.text()
        phone = self.lineEdit_2.text()
        email = self.lineEdit_3.text()
        age = self.lineEdit_4.text()

        if len(fio) == 0:
            print("Введите ФИО!")
            return
        
        if len(phone) == 0:
            print("Введите номер телефона!")
            return
        
        if len(email) == 0:
            print("Введите Email!")
            return
        
        if len(age) == 0:
            print("Введите Возраст!")
            return

        mycursor.execute(f'INSERT INTO `statement` (fio, phone,  email, age) VALUES ("{fio}", "{phone}", "{email}","{age}")')
        print("Успешно отправлено!")
        mydb.commit()

######## Ограничитель ###############################

# ФИО   
    def fio(self):
        reg_ex = QRegExp("[а-я А-Я]{1000}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit)
        self.lineEdit.setValidator(input_validator)

# Телефон
    def phone(self):
        reg_ex = QRegExp("[0-9 +()-]{20}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_2)
        self.lineEdit_2.setValidator(input_validator)

# Email
    def email(self):
        reg_ex = QRegExp("[a-zA-Z@._-0-9]{150}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_3)
        self.lineEdit_3.setValidator(input_validator)

# Возраст
    def age(self):
        reg_ex = QRegExp("[0-9]{3}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_4)
        self.lineEdit_4.setValidator(input_validator)

#################################

#################

    def download(self, book_link, book_name):
        the_book = requests.get(book_link, stream=True)
        with open(book_name, 'wb') as f:
             for chunk in the_book.iter_content(1024 * 1024 * 2):  # 2 MB chunks
                  f.write(chunk)

        print ("+")

    def retranslateUi(self, MainStudentWindow):
        _translate = QtCore.QCoreApplication.translate
        MainStudentWindow.setWindowTitle(_translate("MainStudentWindow", "FoxSkill"))
        self.pushButton_17.setText(_translate("MainStudentWindow", "Уроки"))
        self.label_2.setText(_translate("MainStudentWindow", "Меню"))
        self.pushButton_13.setText(_translate("MainStudentWindow", "Подать заявление"))
        self.pushButton_12.setText(_translate("MainStudentWindow", "Сайт КТК"))
        self.pushButton_15.setText(_translate("MainStudentWindow", "Выйти"))
        self.label_9.setText(_translate("MainStudentWindow", "Подача заявления на курс"))
        self.label_10.setText(_translate("MainStudentWindow", "ФИО"))
        self.label_11.setText(_translate("MainStudentWindow", "Телефон"))
        self.label_12.setText(_translate("MainStudentWindow", "Почта"))
        self.label_13.setText(_translate("MainStudentWindow", "Возраст"))
        self.pushButton_31.setText(_translate("MainStudentWindow", "Подать заявление"))
        self.pushButton_32.setText(_translate("MainStudentWindow", "Назад"))
        self.label_3.setText(_translate("MainStudentWindow", "Unit 1"))
        self.pushButton_25.setText(_translate("MainStudentWindow", "Скачать урок"))
        self.label_6.setText(_translate("MainStudentWindow", "Unit 2"))
        self.pushButton_28.setText(_translate("MainStudentWindow", "Купить урок"))
        self.label_4.setText(_translate("MainStudentWindow", "Unit 3"))
        self.pushButton_26.setText(_translate("MainStudentWindow", "Купить урок"))
        self.label_7.setText(_translate("MainStudentWindow", "Unit 4"))
        self.pushButton_29.setText(_translate("MainStudentWindow", "Купить урок"))
        self.label_5.setText(_translate("MainStudentWindow", "Unit 5"))
        self.pushButton_27.setText(_translate("MainStudentWindow", "Купить урок"))
        self.label_8.setText(_translate("MainStudentWindow", "Unit 6"))
        self.pushButton_30.setText(_translate("MainStudentWindow", "Купить урок"))
        self.pushButton_24.setText(_translate("MainStudentWindow", "Купить все уроки"))
        self.pushButton_23.setText(_translate("MainStudentWindow", "Назад"))
import img_py.img_logo_rc
