# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import QDateTime,QDate, QTime, Qt, QRegExp
from PyQt5.QtWidgets import QTableWidgetItem, QApplication, QDialog, QMainWindow, QMessageBox, QPushButton
from PyQt5.QtGui import QRegExpValidator

from update_users import Ui_UpdateUserWindow
from add_user import Ui_RegWindow
from exit_teacher import Ui_ExitWindow
import pandas as pd

import webbrowser

import requests
from functools import partial

# DOCX
import docx # Подключение к docx
from docx.shared import Pt # Подключение размер шрифта

# ПОДКЛЮЧЕНИЕ К БД
import mysql.connector as mc

mydb = mc.connect(
     host="localhost",
     user="root",
     password="",
     database="foxskill"
)
print("Успешное подключение БД - Главное окно Учителя")
mycursor = mydb.cursor()

class Ui_MainTeacherWindow(object):
    
    def AddUserWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_RegWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def UpdateUserWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_UpdateUserWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def ExitWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ExitWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainTeacherWindow):
        MainTeacherWindow.setObjectName("MainTeacherWindow")
        MainTeacherWindow.resize(1100, 600)
        MainTeacherWindow.setMinimumSize(QtCore.QSize(1100, 600))
        MainTeacherWindow.setMaximumSize(QtCore.QSize(1100, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainTeacherWindow.setWindowIcon(icon)
        MainTeacherWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainTeacherWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.525, y1:0, x2:0.537, y2:1, stop:0 rgba(209, 47, 8, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setStyleSheet("background-color: 0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(18, 18, 18, 18)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(200, 50))
        self.label.setMaximumSize(QtCore.QSize(200, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/img/logo_text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: 0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setMinimumSize(QtCore.QSize(300, 385))
        self.frame_7.setMaximumSize(QtCore.QSize(300, 385))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)

###########

        self.pushButton_17 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page_3))

##############

        self.pushButton_17.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_17.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 1, 0, 1, 1)

##############

        self.pushButton_19 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page_4))
        self.pushButton_19.clicked.connect(self.history_buy_data)

##############

        self.pushButton_19.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_19.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 2, 0, 1, 1)

############

        self.pushButton_12 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_12.clicked.connect(lambda: webbrowser.open('https://ktk40.ru/index.php/ru/'))

#################

        self.pushButton_12.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_12.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 3, 0, 1, 1)

#############

        self.pushButton_13 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page_5))
        self.pushButton_13.clicked.connect(self.statement_data)

#############

        self.pushButton_13.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_13.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 4, 0, 1, 1)

##############

        self.pushButton_14 = QtWidgets.QPushButton(self.frame_7, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page_2))
        self.pushButton_14.clicked.connect(self.student_data)

##############

        self.pushButton_14.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_14.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 5, 0, 1, 1)

###############

        self.pushButton_15 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_15.clicked.connect(self.ExitWindow)
        self.pushButton_15.clicked.connect(MainTeacherWindow.close)

################

        self.pushButton_15.setMinimumSize(QtCore.QSize(250, 50))
        self.pushButton_15.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_7, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(29, 125, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_32 = QtWidgets.QFrame(self.page_5)
        self.frame_32.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_32)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_28.addWidget(self.lineEdit_3)

#############

        self.pushButton_31 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_31.clicked.connect(self.search_statement)

###############

        self.pushButton_31.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_31.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_28.addWidget(self.pushButton_31)
        self.verticalLayout_9.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.page_5)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_29.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_34)
        self.tableWidget_3.setStyleSheet("border: 0;")
        self.tableWidget_3.setRowCount(7)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(191)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_29.addWidget(self.tableWidget_3)
        self.verticalLayout_8.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_33)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem2)

#############

        self.pushButton_32 = QtWidgets.QPushButton(self.frame_35)
        self.pushButton_32.clicked.connect(self.exportToExcel_history_statement)

##############

        self.pushButton_32.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_32.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_30.addWidget(self.pushButton_32)

#############

        self.pushButton_33 = QtWidgets.QPushButton(self.frame_35)
        self.pushButton_33.clicked.connect(self.statement_data)

#############

        self.pushButton_33.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_33.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_30.addWidget(self.pushButton_33)

############

        self.pushButton_34 = QtWidgets.QPushButton(self.frame_35, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page))

###############

        self.pushButton_34.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_34.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_30.addWidget(self.pushButton_34)
        self.verticalLayout_8.addWidget(self.frame_35)
        self.verticalLayout_9.addWidget(self.frame_33)
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.page_4)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)

##########

        self.pushButton_22 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_22.clicked.connect(self.search_history_buy)

############

        self.pushButton_22.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_22.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_8.addWidget(self.pushButton_22)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.frame_8 = QtWidgets.QFrame(self.page_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_9)
        self.tableWidget_2.setStyleSheet("border: 0;")
        self.tableWidget_2.setRowCount(7)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(191)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_6.addWidget(self.tableWidget_2)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)

##############

        self.pushButton_18 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_18.clicked.connect(self.exportToExcel_history_buy)

###############

        self.pushButton_18.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_18.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_7.addWidget(self.pushButton_18)

#############

        self.pushButton_20 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_20.clicked.connect(self.history_buy_data)
        
##############

        self.pushButton_20.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_20.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_7.addWidget(self.pushButton_20)

###########

        self.pushButton_21 = QtWidgets.QPushButton(self.frame_10, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page))

#############

        self.pushButton_21.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_21.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_7.addWidget(self.pushButton_21)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setStyleSheet("border: 0;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1098, 518))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 518))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_14.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.frame_15)
        self.label_3.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.horizontalLayout_10.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")

###########

        self.pushButton_25 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_25.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 1.docx"))

###########

        self.pushButton_25.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_25.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_12.addWidget(self.pushButton_25)
        self.horizontalLayout_10.addWidget(self.frame_16)
        self.gridLayout_3.addWidget(self.frame_14, 0, 0, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.frame_12)
        self.frame_23.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_6 = QtWidgets.QLabel(self.frame_24)
        self.label_6.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_20.addWidget(self.label_6)
        self.horizontalLayout_19.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.frame_23)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")

#############

        self.pushButton_28 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_28.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 2.docx"))

#############

        self.pushButton_28.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_28.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_21.addWidget(self.pushButton_28)
        self.horizontalLayout_19.addWidget(self.frame_25)
        self.gridLayout_3.addWidget(self.frame_23, 0, 1, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame_12)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_17.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.frame_18)
        self.label_4.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.horizontalLayout_13.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")

##################

        self.pushButton_26 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_26.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 3.docx"))

####################

        self.pushButton_26.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_26.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_15.addWidget(self.pushButton_26)
        self.horizontalLayout_13.addWidget(self.frame_19)
        self.gridLayout_3.addWidget(self.frame_17, 1, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.frame_12)
        self.frame_26.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_7 = QtWidgets.QLabel(self.frame_27)
        self.label_7.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_23.addWidget(self.label_7)
        self.horizontalLayout_22.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")

#############

        self.pushButton_29 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_29.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 4.docx"))

##############

        self.pushButton_29.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_29.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_24.addWidget(self.pushButton_29)
        self.horizontalLayout_22.addWidget(self.frame_28)
        self.gridLayout_3.addWidget(self.frame_26, 1, 1, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.frame_12)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_20.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.frame_21)
        self.label_5.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.horizontalLayout_16.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")

#############

        self.pushButton_27 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_27.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 5.docx"))

#############

        self.pushButton_27.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_27.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_18.addWidget(self.pushButton_27)
        self.horizontalLayout_16.addWidget(self.frame_22)
        self.gridLayout_3.addWidget(self.frame_20, 2, 0, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.frame_12)
        self.frame_29.setStyleSheet("background-color: #DEDEDE;\n"
"border-radius: 15px;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_8 = QtWidgets.QLabel(self.frame_30)
        self.label_8.setStyleSheet("font: 63 18pt \"Montserrat SemiBold\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_26.addWidget(self.label_8)
        self.horizontalLayout_25.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")

#############

        self.pushButton_30 = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_30.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 6.docx"))

############

        self.pushButton_30.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_30.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_27.addWidget(self.pushButton_30)
        self.horizontalLayout_25.addWidget(self.frame_31)
        self.gridLayout_3.addWidget(self.frame_29, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setSpacing(12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)


        self.pushButton_24 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_24.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 1.docx"))
        self.pushButton_24.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 2.docx"))
        self.pushButton_24.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 3.docx"))
        self.pushButton_24.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 4.docx"))
        self.pushButton_24.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 5.docx"))
        self.pushButton_24.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 6.docx"))

        self.pushButton_24.setMinimumSize(QtCore.QSize(225, 50))
        self.pushButton_24.setMaximumSize(QtCore.QSize(225, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_9.addWidget(self.pushButton_24)

#############

        self.pushButton_23 = QtWidgets.QPushButton(self.frame_13, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page))

############

        self.pushButton_23.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_23.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_9.addWidget(self.pushButton_23)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.page_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)

#############

        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.clicked.connect(self.search_student)

###############

        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_7.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setStyleSheet("border: 0;")
        self.tableWidget.setRowCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(143)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

###########

        self.pushButton_11 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_11.clicked.connect(self.AddUserWindow)

##############

        self.pushButton_11.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_11.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_5.addWidget(self.pushButton_11)

############

        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_8.clicked.connect(self.UpdateUserWindow)
        
##############

        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)

############

        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.clicked.connect(self.user_data_delete)

############

        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_9.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)

#############

        self.pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_10.clicked.connect(self.student_data)

#############

        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_10.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)

################

        self.pushButton_16 = QtWidgets.QPushButton(self.frame_6, clicked = lambda: self.stackedWidget.setCurrentWidget(self.page))

###############

        self.pushButton_16.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_16.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_5.addWidget(self.pushButton_16)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        MainTeacherWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainTeacherWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainTeacherWindow)

 ################# EXCEL FILE ############################################

# pay

    def exportToExcel_history_buy(self):
            columnHeaders = []

            # create column header list
            for j in range(self.tableWidget_2.model().columnCount()):
                columnHeaders.append(self.tableWidget_2.horizontalHeaderItem(j).text())

            df = pd.DataFrame(columns=columnHeaders)

            # create dataframe object recordset
            for row in range(self.tableWidget_2.rowCount()):
                for col in range(self.tableWidget_2.columnCount()):
                    df.at[row, columnHeaders[col]] = self.tableWidget_2.item(row, col).text()

            df.to_excel('pay.xlsx', index=False)
            print('Excel file exported')

# pay

    def exportToExcel_history_statement(self):
            columnHeaders = []

            # create column header list
            for j in range(self.tableWidget_3.model().columnCount()):
                columnHeaders.append(self.tableWidget_3.horizontalHeaderItem(j).text())

            df = pd.DataFrame(columns=columnHeaders)

            # create dataframe object recordset
            for row in range(self.tableWidget_3.rowCount()):
                for col in range(self.tableWidget_3.columnCount()):
                    df.at[row, columnHeaders[col]] = self.tableWidget_3.item(row, col).text()

            df.to_excel('statement.xlsx', index=False)
            print('Excel file exported')

################# ТАБЛИЦА ###############################################

    def statement_data(self):
        mycursor.execute(f"SELECT * FROM statement")
                    
        result = mycursor.fetchall()

        mydb.commit()

        self.tableWidget_3.setRowCount(0)
 
        for row_number, row_data in enumerate(result):
                self.tableWidget_3.insertRow(row_number)
 
                for column_number ,data in enumerate(row_data):
                     self.tableWidget_3.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        
        print("+")

################## ПОИСК ################################################

    def search_statement(self):
        
        fio = self.lineEdit_3.text()
        phone = self.lineEdit_3.text()
        email = self.lineEdit_3.text()
        age = self.lineEdit_3.text()

        mycursor.execute(f'SELECT * FROM `statement` WHERE (fio = "{fio}") OR (phone = "{phone}") OR (email = "{email}") OR (age = "{age}")')

                    
        result = mycursor.fetchall()
        mydb.commit()

        self.tableWidget_3.setRowCount(0)
 
        for row_number, row_data in enumerate(result):
                self.tableWidget_3.insertRow(row_number)
 
                for column_number ,data in enumerate(row_data):
                     self.tableWidget_3.setItem(row_number, column_number, QTableWidgetItem(str(data)))

                
        print ("+")

#########################################


################# ТАБЛИЦА ###############################################

    def student_data(self):
        mycursor.execute(f"SELECT * FROM user")
                    
        result = mycursor.fetchall()

        mydb.commit()

        self.tableWidget.setRowCount(0)
 
        for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
 
                for column_number ,data in enumerate(row_data):
                     self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        
        print("+")

#################### DELETE ############################################

    def user_data_delete(self):
        
        row_2 = self.tableWidget.currentRow()
        del_d = self.tableWidget.item(row_2, 0).text()
                    
        query = "DELETE FROM user WHERE id = '"+del_d+"'"
                    
        mycursor.execute(query)
                    
        mydb.commit()
        self.tableWidget.removeRow(row_2)
        print("Успешное удаление!")

################## ПОИСК ################################################

    def search_student(self):
        
        fio = self.lineEdit.text()
        phone = self.lineEdit.text()
        email = self.lineEdit.text()
        data_born = self.lineEdit.text()
        login = self.lineEdit.text()
        password = self.lineEdit.text()

        mycursor.execute(f'SELECT * FROM `user` WHERE (fio = "{fio}") OR (phone = "{phone}") OR (email = "{email}") OR (data_born = "{data_born}") OR (login = "{login}") OR (password = "{password}")')

                    
        result = mycursor.fetchall()
        mydb.commit()

        self.tableWidget.setRowCount(0)
 
        for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
 
                for column_number ,data in enumerate(row_data):
                     self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))

        print ("+")


#########################################
                     
################# ТАБЛИЦА ###############################################

    def history_buy_data(self):
        mycursor.execute(f"SELECT * FROM pay")
                    
        result = mycursor.fetchall()

        mydb.commit()

        self.tableWidget_2.setRowCount(0)
 
        for row_number, row_data in enumerate(result):
                self.tableWidget_2.insertRow(row_number)
 
                for column_number ,data in enumerate(row_data):
                     self.tableWidget_2.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        
        print("+")

################## ПОИСК ################################################

    def search_history_buy(self):
        
        fio = self.lineEdit_2.text()
        email = self.lineEdit_2.text()
        data = self.lineEdit_2.text()
        sum = self.lineEdit_2.text()

        mycursor.execute(f'SELECT * FROM `pay` WHERE (fio = "{fio}") OR (email = "{email}") OR (sum = "{sum}")')

                    
        result = mycursor.fetchall()
        mydb.commit()

        self.tableWidget_2.setRowCount(0)
 
        for row_number, row_data in enumerate(result):
                self.tableWidget_2.insertRow(row_number)
 
                for column_number ,data in enumerate(row_data):
                     self.tableWidget_2.setItem(row_number, column_number, QTableWidgetItem(str(data)))

        print ("+")


#################

    def download(self, book_link, book_name):
        the_book = requests.get(book_link, stream=True)
        with open(book_name, 'wb') as f:
             for chunk in the_book.iter_content(1024 * 1024 * 2):  # 2 MB chunks
                  f.write(chunk)

        print ("+")

    def retranslateUi(self, MainTeacherWindow):
        _translate = QtCore.QCoreApplication.translate
        MainTeacherWindow.setWindowTitle(_translate("MainTeacherWindow", "FoxSkill"))
        self.label_2.setText(_translate("MainTeacherWindow", "Админская панель"))
        self.pushButton_17.setText(_translate("MainTeacherWindow", "Уроки"))
        self.pushButton_19.setText(_translate("MainTeacherWindow", "История покупок"))
        self.pushButton_12.setText(_translate("MainTeacherWindow", "Сайт КТК"))
        self.pushButton_13.setText(_translate("MainTeacherWindow", "Заявление"))
        self.pushButton_14.setText(_translate("MainTeacherWindow", "Список учеников"))
        self.pushButton_15.setText(_translate("MainTeacherWindow", "Выйти"))
        self.lineEdit_3.setPlaceholderText(_translate("MainTeacherWindow", "Поиск"))
        self.pushButton_31.setText(_translate("MainTeacherWindow", "Найти"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainTeacherWindow", "ФИО"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainTeacherWindow", "Телефон"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainTeacherWindow", "Email"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainTeacherWindow", "Возраст"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainTeacherWindow", "Дата подачи"))
        self.pushButton_32.setText(_translate("MainTeacherWindow", "Печать"))
        self.pushButton_33.setText(_translate("MainTeacherWindow", "Обновить"))
        self.pushButton_34.setText(_translate("MainTeacherWindow", "Назад"))
        self.lineEdit_2.setPlaceholderText(_translate("MainTeacherWindow", "Поиск"))
        self.pushButton_22.setText(_translate("MainTeacherWindow", "Найти"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainTeacherWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainTeacherWindow", "ФИО"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainTeacherWindow", "Email"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainTeacherWindow", "Дата"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainTeacherWindow", "Сумма"))
        self.pushButton_18.setText(_translate("MainTeacherWindow", "Печать"))
        self.pushButton_20.setText(_translate("MainTeacherWindow", "Обновить"))
        self.pushButton_21.setText(_translate("MainTeacherWindow", "Назад"))
        self.label_3.setText(_translate("MainTeacherWindow", "Unit 1"))
        self.pushButton_25.setText(_translate("MainTeacherWindow", "Скачать урок"))
        self.label_6.setText(_translate("MainTeacherWindow", "Unit 2"))
        self.pushButton_28.setText(_translate("MainTeacherWindow", "Скачать урок"))
        self.label_4.setText(_translate("MainTeacherWindow", "Unit 3"))
        self.pushButton_26.setText(_translate("MainTeacherWindow", "Скачать урок"))
        self.label_7.setText(_translate("MainTeacherWindow", "Unit 4"))
        self.pushButton_29.setText(_translate("MainTeacherWindow", "Скачать урок"))
        self.label_5.setText(_translate("MainTeacherWindow", "Unit 5"))
        self.pushButton_27.setText(_translate("MainTeacherWindow", "Скачать урок"))
        self.label_8.setText(_translate("MainTeacherWindow", "Unit 6"))
        self.pushButton_30.setText(_translate("MainTeacherWindow", "Скачать урок"))
        self.pushButton_24.setText(_translate("MainTeacherWindow", "Скачать все уроки"))
        self.pushButton_23.setText(_translate("MainTeacherWindow", "Назад"))
        self.lineEdit.setPlaceholderText(_translate("MainTeacherWindow", "Поиск"))
        self.pushButton_7.setText(_translate("MainTeacherWindow", "Найти"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainTeacherWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainTeacherWindow", "ФИО"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainTeacherWindow", "Телефон"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainTeacherWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainTeacherWindow", "Дата рождения"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainTeacherWindow", "Логин"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainTeacherWindow", "Пароль"))
        self.pushButton_11.setText(_translate("MainTeacherWindow", "Добавить"))
        self.pushButton_8.setText(_translate("MainTeacherWindow", "Редактировать"))
        self.pushButton_9.setText(_translate("MainTeacherWindow", "Удалить"))
        self.pushButton_10.setText(_translate("MainTeacherWindow", "Обновить"))
        self.pushButton_16.setText(_translate("MainTeacherWindow", "Назад"))
import img_py.img_logo_rc
