# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\pay.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime,QDate, QTime, Qt, QRegExp
from PyQt5.QtGui import QRegExpValidator

import requests
from functools import partial

# Подключение БД
import mysql.connector as mc

mydb = mc.connect(
     host="localhost",
     user="root",
     password="",
     database="foxskill"
)
print("Успешное подключение БД - Оплата")
mycursor = mydb.cursor()

# DOCX
import docx # Подключение к docx
from docx.shared import Pt # Подключение размер шрифта

class Ui_PayWindow(object):
    def setupUi(self, PayWindow):
        PayWindow.setObjectName("PayWindow")
        PayWindow.resize(515, 610)
        PayWindow.setMinimumSize(QtCore.QSize(515, 610))
        PayWindow.setMaximumSize(QtCore.QSize(515, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PayWindow.setWindowIcon(icon)
        PayWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(PayWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.525, y1:0, x2:0.537, y2:1, stop:0 rgba(209, 47, 8, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: 0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setStyleSheet("    font: 63 20pt \"Montserrat SemiBold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("\n"
"background-color: 0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_7.setSpacing(25)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_3.setSpacing(16)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setStyleSheet("font: 63 14pt \"Montserrat SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_2.setMouseTracking(False)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_3.setStyleSheet("background-color: 0;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

##########

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.clicked.connect(self.insert_pay)
        self.pushButton_3.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 1.docx"))
        self.pushButton_3.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 2.docx"))
        self.pushButton_3.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 3.docx"))
        self.pushButton_3.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 4.docx"))
        self.pushButton_3.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 5.docx"))
        self.pushButton_3.clicked.connect(partial(self.download,"https://drive.google.com/uc?export=download&id=1VWsAJaNJJaaf4Gs3_xiQkrA3jFStaHOo", "Unit 6.docx"))

############

        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)

##########

        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.clicked.connect(PayWindow.close)

##########

        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        PayWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PayWindow)
        QtCore.QMetaObject.connectSlotsByName(PayWindow)

######################## БД ################################################

    def insert_pay(self):

        # Время
        tim = QTime.currentTime()
        tm = tim.toString()
        
        # Дата
        date = QDate.currentDate()
        dt = date.toString(Qt.ISODate)

        fio = self.lineEdit.text()
        email = self.lineEdit_4.text()
        sum = self.lineEdit_2.text()

        if len(fio) == 0:
            self.label.setText("Введите ФИО!")
            return
        
        if len(email) == 0:
            self.label.setText("Введите Email!")
            return
        
        if len(email) == 0:
            self.label.setText("Введите Email!")
            return
        
        try:
            query = "INSERT INTO pay (fio, email, sum) VALUES (%s, %s, %s)"
            value = (fio, email, sum)
            
            mycursor.execute(query, value)
            mydb.commit()

            self.label.setText("Успешно оплачено!")
            
############ ЧЕК ###################################################
            
            doc = docx.Document()
            style = doc.styles['Normal'] # Стили текста
            style.font.name = 'Courier New CYR' # Шрифт
            style.font.size = Pt(20) # Размер шрифта
            
            doc.add_paragraph('ООО "FoxSkill"') # ЗАГОЛОВОК

            par1 = doc.add_paragraph('')
            par2 = doc.add_paragraph('')
            par3 = doc.add_paragraph('')
            par4 = doc.add_paragraph('')
            par5 = doc.add_paragraph('')
            par7 = doc.add_paragraph('')
            par10 = doc.add_paragraph('')
            par11 = doc.add_paragraph('')
            par13 = doc.add_paragraph('')
            par14 = doc.add_paragraph('')
            par15 = doc.add_paragraph('')
            par16 = doc.add_paragraph('')


####### ЗАПОЛНЕНИЕ #################################################

            par1.add_run('Добро пожаловать')
            par2.add_run('ККМ 00000001     #0001')
            par3.add_run('ИНН 0000000000001')
            par4.add_run('      ЭКЛЗ 0000000001')
            par5.add_run(dt +" "+ tm)
            par7.add_run("Покупатель - " + fio)
            par10.add_run('= ' + sum)
            par11.add_run('______________________')
            par13.add_run("ИТОГ          " + sum ).bold=True
            par14.add_run("НАЛИЧ/КАРТОЙ = " + sum)
            par15.add_run('***********************')
            par16.add_run('       00000001# 000001')
 
            doc.save('chek.docx') # Сохранение/скачивание
            

        except mc.Error as e:
            self.label.setText("Ошибка при заполнение!")

################ Ограничитель ###################################################

# Пользователи

    def fio(self):

        reg_ex = QRegExp("[а-я А-Я]{1000}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit)
        self.lineEdit.setValidator(input_validator)

# Админстраторы

    def email(self):

        reg_ex = QRegExp("[a-zA-Z@._-0-9]{150}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_4)
        self.lineEdit_4.setValidator(input_validator)

#####################################################################################
################
        
    def download(self, book_link, book_name):
        the_book = requests.get(book_link, stream=True)
        with open(book_name, 'wb') as f:
             for chunk in the_book.iter_content(1024 * 1024 * 2):  # 2 MB chunks
                  f.write(chunk)

##################

    def retranslateUi(self, PayWindow):
        _translate = QtCore.QCoreApplication.translate
        PayWindow.setWindowTitle(_translate("PayWindow", "Оплата"))
        self.label_5.setText(_translate("PayWindow", "Оплата"))
        self.label_2.setText(_translate("PayWindow", "ФИО"))
        self.label_7.setText(_translate("PayWindow", "Email"))
        self.label_3.setText(_translate("PayWindow", "Сумма"))
        self.lineEdit_2.setText(_translate("PayWindow", "100000 рублей"))
        # self.label.setText(_translate("PayWindow", "Сообщение!"))
        self.pushButton_3.setText(_translate("PayWindow", "Оплатить"))
        self.pushButton_4.setText(_translate("PayWindow", "Назад"))
import img_py.img_logo_rc
