# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\update_users.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

# Подключение БД
import mysql.connector as mc

mydb = mc.connect(
     host="localhost",
     user="root",
     password="",
     database="foxskill"
)
print("Успешное подключение БД - Редактор пользователя")
mycursor = mydb.cursor()

class Ui_UpdateUserWindow(object):
    def setupUi(self, UpdateUserWindow):
        UpdateUserWindow.setObjectName("UpdateUserWindow")
        UpdateUserWindow.resize(800, 840)
        UpdateUserWindow.setMinimumSize(QtCore.QSize(800, 840))
        UpdateUserWindow.setMaximumSize(QtCore.QSize(800, 840))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UpdateUserWindow.setWindowIcon(icon)
        UpdateUserWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(UpdateUserWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.525, y1:0, x2:0.537, y2:1, stop:0 rgba(209, 47, 8, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: 0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/img/logo.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setStyleSheet("    font: 63 20pt \"Montserrat SemiBold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("\n"
"background-color: 0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_5.setContentsMargins(146, -1, 16, -1)
        self.horizontalLayout_5.setSpacing(18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_14)
        self.label_6.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)

##########

        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_3.textChanged.connect(self.id)

##########

        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(120, -1, 16, -1)
        self.horizontalLayout_2.setSpacing(18)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)

###########

        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.textChanged.connect(self.fio)

################

        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(84, -1, 16, -1)
        self.horizontalLayout_6.setSpacing(18)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)

########

        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.textChanged.connect(self.phone)

############

        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setContentsMargins(116, -1, 16, -1)
        self.horizontalLayout_7.setSpacing(18)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        self.label_8.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)

##############

        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_5.textChanged.connect(self.email)

##########

        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_7.addWidget(self.lineEdit_5)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_8.setSpacing(18)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setStyleSheet("    font: 63 14pt \"Montserrat SemiBold\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)

###########

        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_6.textChanged.connect(self.date_born)

##############

        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_8.addWidget(self.lineEdit_6)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setContentsMargins(110, -1, 16, -1)
        self.horizontalLayout_9.setSpacing(18)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setStyleSheet("font: 63 14pt \"Montserrat SemiBold\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)

#############

        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_7.textChanged.connect(self.login_reg)

#############

        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_9.addWidget(self.lineEdit_7)
        self.verticalLayout_3.addWidget(self.frame_13)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(98, -1, 16, -1)
        self.horizontalLayout_3.setSpacing(18)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setStyleSheet("font: 63 14pt \"Montserrat SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)

###############

        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.textChanged.connect(self.phone)

################

        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 0;\n"
"border-radius: 20px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_3.setStyleSheet("background-color: 0;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")

###########

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.clicked.connect(self.update_fio)
        self.pushButton_3.clicked.connect(self.update_email)
        self.pushButton_3.clicked.connect(self.update_data_born)
        self.pushButton_3.clicked.connect(self.update_login)
        self.pushButton_3.clicked.connect(self.update_password)
        self.pushButton_3.clicked.connect(self.update_phone)

##########

        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)

###########

        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.clicked.connect(UpdateUserWindow.close)

##########

        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: #F57A27;\n"
"    border: 0;\n"
"    border-radius: 20px;\n"
"    font: 63 14pt \"Montserrat SemiBold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #D63201;\n"
"    color: #fff;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        UpdateUserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpdateUserWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateUserWindow)

##################### БД #####################################################

    def update_fio(self):
        id = self.lineEdit_3.text()
        fio = self.lineEdit.text()

        if len(id) == 0:
             self.label.setText("Введите ID!")
             return

        if len(fio) == 0:
             print("Пусто! ФИО")
             return
        
        try:
            mycursor.execute("UPDATE user SET fio='" + fio +"' WHERE id=" + id)
            result = mycursor.fetchall
            mydb.commit()

            self.label.setText("Успеешно изменено - ФИО")

        except mc.Error as e:
            print("НЕТ, ПЕРЕДЕЛЫВАЙ! ФИО")


    def update_phone(self):
        id = self.lineEdit_3.text()
        phone = self.lineEdit_4.text()

        if len(id) == 0:
             self.label.setText("Введите ID!")
             return

        if len(phone) == 0:
             print("Пусто! Телефон")
             return
        
        try:
            mycursor.execute("UPDATE user SET phone='" + phone +"' WHERE id=" + id)
            result = mycursor.fetchall
            mydb.commit()

            self.label.setText("Успеешно изменено - Телефон")

        except mc.Error as e:
            print("НЕТ, ПЕРЕДЕЛЫВАЙ! Телефон")


    def update_data_born(self):
        id = self.lineEdit_3.text()
        data_born = self.lineEdit_6.text()

        if len(id) == 0:
             self.label.setText("Введите ID!")
             return

        if len(data_born) == 0:
             print("Пусто! Дата рождения")
             return
        
        try:
            mycursor.execute("UPDATE user SET data_born='" + data_born +"' WHERE id=" + id)
            result = mycursor.fetchall
            mydb.commit()

            self.label.setText("Успеешно изменено - Дата рождения")

        except mc.Error as e:
            print("НЕТ, ПЕРЕДЕЛЫВАЙ! Дата рождения!")

    def update_email(self):
        id = self.lineEdit_3.text()
        email = self.lineEdit_5.text()

        if len(id) == 0:
             self.label.setText("Введите ID!")
             return

        if len(email) == 0:
             print("Пусто! Email")
             return
        
        try:
            mycursor.execute("UPDATE user SET email='" + email +"' WHERE id=" + id)
            result = mycursor.fetchall
            mydb.commit()

            self.label.setText("Успеешно изменено - Email")

        except mc.Error as e:
            print("НЕТ, ПЕРЕДЕЛЫВАЙ! EMAIL")


    def update_login(self):
        id = self.lineEdit_3.text()
        login = self.lineEdit_7.text()

        if len(id) == 0:
             self.label.setText("Введите ID!")
             return

        if len(login) == 0:
             print("Пусто! Логин")
             return
        
        try:
            mycursor.execute("UPDATE user SET login='" + login +"' WHERE id=" + id)
            result = mycursor.fetchall
            mydb.commit()

            self.label.setText("Успеешно изменено - Логин")

        except mc.Error as e:
            print("НЕТ, ПЕРЕДЕЛЫВАЙ! Логин")
    
    def update_password(self):
        id = self.lineEdit_3.text()
        password = self.lineEdit_2.text()

        if len(id) == 0:
             self.label.setText("Введите ID!")
             return

        if len(password) == 0:
             print("Пусто! Пароль")
             return
        
        try:
            mycursor.execute("UPDATE user SET password='" + password +"' WHERE id=" + id)
            result = mycursor.fetchall
            mydb.commit()

            self.label.setText("Успеешно изменено - Пароль")

        except mc.Error as e:
            print("НЕТ, ПЕРЕДЕЛЫВАЙ! Пароль")
        
##############################

# ОГРАНИЧЕНИЕ

###########################################################################

# ID

    def id(self):

        reg_ex = QRegExp("[0-9]{3}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_3)
        self.lineEdit_3.setValidator(input_validator)

# ФИО

    def fio(self):

        reg_ex = QRegExp("[а-я А-Я]{1000}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit)
        self.lineEdit.setValidator(input_validator)

# Телефон

    def phone(self):

        reg_ex = QRegExp("[0-9 +()-]{20}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_4)
        self.lineEdit_4.setValidator(input_validator)

# Дата рожд

    def date_born(self):

        reg_ex = QRegExp("[0-9.]{10}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_6)
        self.lineEdit_6.setValidator(input_validator)

    def login_reg(self):

        reg_ex = QRegExp("[a-zA-Z_0-9]{20}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_7)
        self.lineEdit_7.setValidator(input_validator)
# Email

    def email(self):

        reg_ex = QRegExp("[a-zA-Z@._-0-9]{150}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_2)
        self.lineEdit_2.setValidator(input_validator)

# Пароль

    def password(self):

        reg_ex = QRegExp("[a-zA-Z@._-0-9]{150}")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_2)
        self.lineEdit_2.setValidator(input_validator)

#########################################################################################

    def retranslateUi(self, UpdateUserWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdateUserWindow.setWindowTitle(_translate("UpdateUserWindow", "Редактор"))
        self.label_5.setText(_translate("UpdateUserWindow", "Редактор"))
        self.label_6.setText(_translate("UpdateUserWindow", "ID"))
        self.label_2.setText(_translate("UpdateUserWindow", "ФИО"))
        self.label_7.setText(_translate("UpdateUserWindow", "Телефон"))
        self.label_8.setText(_translate("UpdateUserWindow", "Email"))
        self.label_9.setText(_translate("UpdateUserWindow", "Дата рождения"))
        self.label_10.setText(_translate("UpdateUserWindow", "Логин"))
        self.label_3.setText(_translate("UpdateUserWindow", "Пароль"))
        # self.label.setText(_translate("UpdateUserWindow", "Сообщение!"))
        self.pushButton_3.setText(_translate("UpdateUserWindow", "Создать"))
        self.pushButton_2.setText(_translate("UpdateUserWindow", "Назад"))
import img_py.img_logo_rc
